before:
  hooks:
    - go mod tidy
    - go mod download
    - go install github.com/CycloneDX/cyclonedx-gomod@{{ .Tag }}
    - cyclonedx-gomod -module . -output bom.xml -std
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm64
    flags: |
      -trimpath
    ldflags: |
      -s
      -w
      -extldflags '-static'
      -X github.com/CycloneDX/cyclonedx-gomod/internal/version.Version={{.Tag}}
    mod_timestamp: '{{ .CommitTimestamp }}'
archives:
  - replacements:
      darwin: macos
      386: x86
      amd64: x64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-snapshot"
release:
  extra_files:
    - glob: ./bom.xml
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge pull request'
      - '^Merge branch'
