before:
  hooks:
    - go mod download
    - go mod tidy
    - go install github.com/CycloneDX/cyclonedx-gomod@{{ .Tag }}
    - cyclonedx-gomod -module . -output bom.xml -std
    - cyclonedx-gomod -module . -json -output bom.json -std
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
    flags: |
      -trimpath
    ldflags: |
      -s
      -w
      -X github.com/CycloneDX/cyclonedx-gomod/internal/version.Version={{ .Tag }}
    mod_timestamp: '{{ .CommitTimestamp }}'
dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "cyclonedx/cyclonedx-gomod:latest"
      - "cyclonedx/cyclonedx-gomod:{{ .Tag }}"
      - "cyclonedx/cyclonedx-gomod:v{{ .Major }}"
      - "cyclonedx/cyclonedx-gomod:v{{ .Major }}.{{ .Minor }}"
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.vendor=CycloneDX"
      - "--label=org.opencontainers.image.url=https://cyclonedx.org"
      - "--label=org.opencontainers.image.source=https://github.com/CycloneDX/cyclonedx-gomod"
    skip_push: true
archives:
  - replacements:
      darwin: macos
      386: x86
      amd64: x64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-snapshot"
release:
  extra_files:
    - glob: ./bom.xml
    - glob: ./bom.json
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge pull request'
      - '^Merge branch'
