name: CI

on: [ push, pull_request ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ "^1.16" ]
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build
        run: make build
      - name: Test
        run: make test
      - name: Generate BOM
        run: make bom
