name: GoReleaser CI

on:
  workflow_dispatch: { }

permissions: { }

jobs:
  goreleaser-ci:
    name: Test Release
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # tag=v3.6.0
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # tag=v4.1.0
      with:
        go-version: "1.20"
        check-latest: true
    - name: Set up QEMU
      uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # tag=v2.2.0
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@7ec5c2b0c6cdda6e8bbb49444bc797dd33d74dd8 # tag=v5.0.0
      with:
        version: latest
        args: release --skip-publish --skip-sign --snapshot