name: GoReleaser CI

on:
  workflow_dispatch: {}

permissions: {}

jobs:
  goreleaser-ci:
    name: Test Release
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.18"
        check-latest: true
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v3.2.0
      with:
        version: 1.10.3
        args: release --skip-publish --skip-sign --snapshot