name: GoReleaser CI

on:
  workflow_dispatch: { }

permissions: { }

jobs:
  goreleaser-ci:
    name: Test Release
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # tag=v3.5.1
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # tag=v4.0.0
      with:
        go-version: "1.18"
        check-latest: true
    - name: Set up QEMU
      uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # tag=v2.1.0
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@f82d6c1c344bcacabba2c841718984797f664a6b # tag=v4.2.0
      with:
        version: latest
        args: release --skip-publish --skip-sign --snapshot