name: GoReleaser CI

on:
  workflow_dispatch: { }

permissions: { }

jobs:
  goreleaser-ci:
    name: Test Release
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # tag=v4.2.1
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # tag=v5.0.2
      with:
        go-version: "1.23"
        check-latest: true
    - name: Set up QEMU
      uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # tag=v3.2.0
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@286f3b13b1b49da4ac219696163fb8c1c93e1200 # tag=v6.0.0
      with:
        version: latest
        args: release --skip publish,sign --snapshot